import { existsSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { ComponentSpec } from '@josephbrendan/schema';
import { formatCode } from './format.js';
import { selectTemplate } from './templates.js';

export interface GenerateComponentsOptions {
  cwd: string;
  components: ComponentSpec[];
  kitName: string;
  exportedAt: string;
  componentsDir: string;
  reactVersion: number;
  hasPathAlias: boolean;
}

export interface GeneratedFileItem {
  relPath: string; // relative to cwd with forward slashes
  content: string;
  componentName?: string;
}

export const CN_HELPER_CODE = `import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
`;

export function generateCnHelper(): string {
  return CN_HELPER_CODE;
}

export function generateBarrelExport(componentNames: string[]): string {
  return (
    componentNames
      .map((name) => `export * from './${name}';`)
      .sort()
      .join('\n') + '\n'
  );
}

export function findOrCreateCnPath(cwd: string): { relPath: string; fullPath: string } {
  // Check if lib/cn.ts or src/lib/cn.ts exists or lib/utils.ts
  const candidates = ['src/lib/cn.ts', 'lib/cn.ts', 'src/lib/utils.ts', 'lib/utils.ts'];

  for (const c of candidates) {
    if (existsSync(join(cwd, c))) {
      return { relPath: c, fullPath: join(cwd, c) };
    }
  }

  // Default to src/lib/cn.ts if src exists, otherwise lib/cn.ts
  const defaultRel = existsSync(join(cwd, 'src')) ? 'src/lib/cn.ts' : 'lib/cn.ts';
  return { relPath: defaultRel, fullPath: join(cwd, defaultRel) };
}

export async function generateComponentFiles(
  opts: GenerateComponentsOptions,
): Promise<GeneratedFileItem[]> {
  const { cwd, components, kitName, exportedAt, componentsDir, reactVersion, hasPathAlias } = opts;
  const files: GeneratedFileItem[] = [];

  // 1. Ensure cn helper
  const cnInfo = findOrCreateCnPath(cwd);
  let cnContent = CN_HELPER_CODE;
  if (existsSync(cnInfo.fullPath)) {
    cnContent = readFileSync(cnInfo.fullPath, 'utf-8');
  }
  files.push({
    relPath: cnInfo.relPath.replace(/\\/g, '/'),
    content: await formatCode(cnContent, cnInfo.fullPath),
  });

  // Calculate cn import path
  let cnImportPath = '@/lib/cn';
  if (hasPathAlias) {
    // If using utils.ts or cn.ts
    const baseName = cnInfo.relPath.replace(/\.tsx?$/, '');
    const withoutSrc = baseName.replace(/^src\//, '');
    cnImportPath = `@/${withoutSrc}`;
  } else {
    // Relative path from componentsDir to cn helper
    const compDirAbs = join(cwd, componentsDir);
    let rel = relative(compDirAbs, cnInfo.fullPath)
      .replace(/\\/g, '/')
      .replace(/\.tsx?$/, '');
    if (!rel.startsWith('.')) rel = `./${rel}`;
    cnImportPath = rel;
  }

  // 2. Generate each component
  const exportNames: string[] = [];

  for (const spec of components) {
    const rawCode = selectTemplate({
      spec,
      kitName,
      exportedAt,
      reactVersion,
      cnImportPath,
    });

    const compFileRel = join(componentsDir, `${spec.name}.tsx`).replace(/\\/g, '/');
    const formatted = await formatCode(rawCode, join(cwd, compFileRel));

    files.push({
      relPath: compFileRel,
      content: formatted,
      componentName: spec.name,
    });

    exportNames.push(spec.name);
  }

  // 3. Generate barrel export index.ts
  const barrelLines = exportNames
    .map((name) => `export * from './${name}.js';`)
    .sort()
    .join('\n');

  const barrelHeader = `// Generated by Frame-Relay from ${kitName}, exported ${exportedAt}. Safe to edit. Sync keeps your changes.\n`;
  const barrelRel = join(componentsDir, 'index.ts').replace(/\\/g, '/');
  const formattedBarrel = await formatCode(`${barrelHeader}${barrelLines}\n`, join(cwd, barrelRel));

  files.push({
    relPath: barrelRel,
    content: formattedBarrel,
  });

  return files;
}
