import { ComponentSpec } from '@josephbrendan/schema';
import { buildCvaDefinition } from './cva.js';

export interface TemplateContext {
  spec: ComponentSpec;
  kitName: string;
  exportedAt: string;
  reactVersion: number;
  cnImportPath: string;
}

function makeHeader(ctx: TemplateContext, hasRaw: boolean, isGeneric = false): string {
  const lines = [
    `// Generated by Frame-Relay from ${ctx.kitName}, exported ${ctx.exportedAt}. Safe to edit. Sync keeps your changes.`,
  ];
  if (isGeneric) {
    lines.push(
      '// frame-relay: generated shell. Agent: refine using .frame-relay/components.md and the screenshots.',
    );
  }
  if (hasRaw) {
    lines.push(
      '// frame-relay: raw value from Figma. Bind it to a variable in Figma to use a token.',
    );
  }
  return lines.join('\n');
}

function getVariantHelpers(variantKeys: string[]) {
  const destructure = variantKeys.length > 0 ? variantKeys.join(', ') + ', ' : '';
  const args = variantKeys.length > 0 ? `{ ${variantKeys.join(', ')} }` : '{}';
  return { destructure, args };
}

export function renderButtonTemplate(ctx: TemplateContext): string {
  const { spec, reactVersion, cnImportPath } = ctx;
  const cva = buildCvaDefinition(spec, 'buttonVariants', [
    'inline-flex',
    'items-center',
    'justify-center',
    'cursor-pointer',
    'transition-colors',
    'focus-visible:outline-none',
    'disabled:pointer-events-none',
  ]);

  const header = makeHeader(ctx, cva.hasRaw);
  const isReact19 = reactVersion >= 19;
  const vKeys = cva.variantTypeProps.length > 0 ? cva.variantTypeProps : ['variant', 'size'];
  const { destructure: vDestructure, args: vArgs } = getVariantHelpers(vKeys);

  return `${header}
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '${cnImportPath}';

${cva.cvaCode}

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  leftIcon?: React.ReactNode;
  rightIcon?: React.ReactNode;
  loading?: boolean;
}

${
  isReact19
    ? `export function Button({
  className,
  ${vDestructure}leftIcon,
  rightIcon,
  loading = false,
  disabled,
  children,
  type = 'button',
  ref,
  ...props
}: ButtonProps & { ref?: React.Ref<HTMLButtonElement> }) {
  return (
    <button
      ref={ref}
      type={type}
      disabled={disabled || loading}
      data-loading={loading ? 'true' : undefined}
      className={cn(buttonVariants(${vArgs}), className)}
      {...props}
    >
      {leftIcon && <span className="mr-2 inline-flex items-center shrink-0">{leftIcon}</span>}
      {children}
      {rightIcon && <span className="ml-2 inline-flex items-center shrink-0">{rightIcon}</span>}
    </button>
  );
}`
    : `export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, ${vDestructure}leftIcon, rightIcon, loading = false, disabled, children, type = 'button', ...props }, ref) => {
    return (
      <button
        ref={ref}
        type={type}
        disabled={disabled || loading}
        data-loading={loading ? 'true' : undefined}
        className={cn(buttonVariants(${vArgs}), className)}
        {...props}
      >
        {leftIcon && <span className="mr-2 inline-flex items-center shrink-0">{leftIcon}</span>}
        {children}
        {rightIcon && <span className="ml-2 inline-flex items-center shrink-0">{rightIcon}</span>}
      </button>
    );
  }
);
Button.displayName = 'Button';`
}
`;
}

export function renderInputTemplate(ctx: TemplateContext): string {
  const { spec, reactVersion, cnImportPath } = ctx;
  const cva = buildCvaDefinition(spec, 'inputVariants', [
    'flex',
    'w-full',
    'transition-colors',
    'focus-visible:outline-none',
    'disabled:cursor-not-allowed',
    'disabled:opacity-50',
  ]);

  const header = makeHeader(ctx, cva.hasRaw);
  const isReact19 = reactVersion >= 19;
  const { destructure: vDestructure, args: vArgs } = getVariantHelpers(cva.variantTypeProps);

  return `${header}
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '${cnImportPath}';

${cva.cvaCode}

export interface InputProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'size'>,
    VariantProps<typeof inputVariants> {
  label?: string;
  helperText?: string;
  error?: boolean | string;
  leftIcon?: React.ReactNode;
  rightIcon?: React.ReactNode;
}

${
  isReact19
    ? `export function Input({
  className,
  type = 'text',
  ${vDestructure}label,
  helperText,
  error,
  leftIcon,
  rightIcon,
  disabled,
  id,
  ref,
  ...props
}: InputProps & { ref?: React.Ref<HTMLInputElement> }) {
  const generatedId = React.useId();
  const inputId = id || generatedId;
  const isError = Boolean(error);
  const errorMessage = typeof error === 'string' ? error : helperText;

  return (
    <div className="flex flex-col gap-1.5 w-full">
      {label && (
        <label htmlFor={inputId} className="text-sm font-medium text-foreground">
          {label}
        </label>
      )}
      <div className="relative flex items-center w-full">
        {leftIcon && (
          <span className="absolute left-3 inline-flex items-center pointer-events-none text-muted-foreground">
            {leftIcon}
          </span>
        )}
        <input
          ref={ref}
          id={inputId}
          type={type}
          disabled={disabled}
          aria-invalid={isError ? 'true' : undefined}
          className={cn(
            inputVariants(${vArgs}),
            leftIcon && 'pl-10',
            rightIcon && 'pr-10',
            className
          )}
          {...props}
        />
        {rightIcon && (
          <span className="absolute right-3 inline-flex items-center pointer-events-none text-muted-foreground">
            {rightIcon}
          </span>
        )}
      </div>
      {errorMessage && (
        <p className={cn('text-xs', isError ? 'text-destructive' : 'text-muted-foreground')}>
          {errorMessage}
        </p>
      )}
    </div>
  );
}`
    : `export const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, type = 'text', ${vDestructure}label, helperText, error, leftIcon, rightIcon, disabled, id, ...props }, ref) => {
    const generatedId = React.useId();
    const inputId = id || generatedId;
    const isError = Boolean(error);
    const errorMessage = typeof error === 'string' ? error : helperText;

    return (
      <div className="flex flex-col gap-1.5 w-full">
        {label && (
          <label htmlFor={inputId} className="text-sm font-medium text-foreground">
            {label}
          </label>
        )}
        <div className="relative flex items-center w-full">
          {leftIcon && (
            <span className="absolute left-3 inline-flex items-center pointer-events-none text-muted-foreground">
              {leftIcon}
            </span>
          )}
          <input
            ref={ref}
            id={inputId}
            type={type}
            disabled={disabled}
            aria-invalid={isError ? 'true' : undefined}
            className={cn(
              inputVariants(${vArgs}),
              leftIcon && 'pl-10',
              rightIcon && 'pr-10',
              className
            )}
            {...props}
          />
          {rightIcon && (
            <span className="absolute right-3 inline-flex items-center pointer-events-none text-muted-foreground">
              {rightIcon}
            </span>
          )}
        </div>
        {errorMessage && (
          <p className={cn('text-xs', isError ? 'text-destructive' : 'text-muted-foreground')}>
            {errorMessage}
          </p>
        )}
      </div>
    );
  }
);
Input.displayName = 'Input';`
}
`;
}

export function renderCardTemplate(ctx: TemplateContext): string {
  const { spec, reactVersion, cnImportPath } = ctx;
  const cva = buildCvaDefinition(spec, 'cardVariants', ['overflow-hidden', 'transition-shadow']);

  const header = makeHeader(ctx, cva.hasRaw);
  const isReact19 = reactVersion >= 19;
  const role = spec.accessibility?.role ? `role="${spec.accessibility.role}"` : '';
  const { destructure: vDestructure, args: vArgs } = getVariantHelpers(cva.variantTypeProps);

  return `${header}
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '${cnImportPath}';

${cva.cvaCode}

export interface CardProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof cardVariants> {
  header?: React.ReactNode;
  footer?: React.ReactNode;
}

${
  isReact19
    ? `export function Card({ className, ${vDestructure}header, footer, children, ref, ...props }: CardProps & { ref?: React.Ref<HTMLDivElement> }) {
  return (
    <div ref={ref} ${role} className={cn(cardVariants(${vArgs}), className)} {...props}>
      {header && <div className="border-b border-border p-4 font-semibold">{header}</div>}
      <div className="p-4">{children}</div>
      {footer && <div className="border-t border-border p-4">{footer}</div>}
    </div>
  );
}`
    : `export const Card = React.forwardRef<HTMLDivElement, CardProps>(
  ({ className, ${vDestructure}header, footer, children, ...props }, ref) => {
    return (
      <div ref={ref} ${role} className={cn(cardVariants(${vArgs}), className)} {...props}>
        {header && <div className="border-b border-border p-4 font-semibold">{header}</div>}
        <div className="p-4">{children}</div>
        {footer && <div className="border-t border-border p-4">{footer}</div>}
      </div>
    );
  }
);
Card.displayName = 'Card';`
}
`;
}

export function renderBadgeTemplate(ctx: TemplateContext): string {
  const { spec, reactVersion, cnImportPath } = ctx;
  const cva = buildCvaDefinition(spec, 'badgeVariants', [
    'inline-flex',
    'items-center',
    'justify-center',
    'font-medium',
  ]);

  const header = makeHeader(ctx, cva.hasRaw);
  const isReact19 = reactVersion >= 19;
  const role = spec.accessibility?.role || 'status';
  const { destructure: vDestructure, args: vArgs } = getVariantHelpers(cva.variantTypeProps);

  return `${header}
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '${cnImportPath}';

${cva.cvaCode}

export interface BadgeProps
  extends React.HTMLAttributes<HTMLSpanElement>,
    VariantProps<typeof badgeVariants> {}

${
  isReact19
    ? `export function Badge({ className, ${vDestructure}children, ref, ...props }: BadgeProps & { ref?: React.Ref<HTMLSpanElement> }) {
  return (
    <span ref={ref} role="${role}" className={cn(badgeVariants(${vArgs}), className)} {...props}>
      {children}
    </span>
  );
}`
    : `export const Badge = React.forwardRef<HTMLSpanElement, BadgeProps>(
  ({ className, ${vDestructure}children, ...props }, ref) => {
    return (
      <span ref={ref} role="${role}" className={cn(badgeVariants(${vArgs}), className)} {...props}>
        {children}
      </span>
    );
  }
);
Badge.displayName = 'Badge';`
}
`;
}

export function renderTextareaTemplate(ctx: TemplateContext): string {
  const { spec, reactVersion, cnImportPath } = ctx;
  const cva = buildCvaDefinition(spec, 'textareaVariants', [
    'flex',
    'w-full',
    'min-h-[80px]',
    'focus-visible:outline-none',
    'disabled:cursor-not-allowed',
    'disabled:opacity-50',
  ]);
  const header = makeHeader(ctx, cva.hasRaw);
  const isReact19 = reactVersion >= 19;
  const { destructure: vDestructure, args: vArgs } = getVariantHelpers(cva.variantTypeProps);

  return `${header}
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '${cnImportPath}';

${cva.cvaCode}

export interface TextareaProps
  extends React.TextareaHTMLAttributes<HTMLTextAreaElement>,
    VariantProps<typeof textareaVariants> {
  label?: string;
  helperText?: string;
  error?: boolean | string;
}

${
  isReact19
    ? `export function Textarea({ className, ${vDestructure}label, helperText, error, disabled, id, ref, ...props }: TextareaProps & { ref?: React.Ref<HTMLTextAreaElement> }) {
  const generatedId = React.useId();
  const inputId = id || generatedId;
  const isError = Boolean(error);
  const errorMessage = typeof error === 'string' ? error : helperText;

  return (
    <div className="flex flex-col gap-1.5 w-full">
      {label && <label htmlFor={inputId} className="text-sm font-medium text-foreground">{label}</label>}
      <textarea
        ref={ref}
        id={inputId}
        disabled={disabled}
        aria-invalid={isError ? 'true' : undefined}
        className={cn(textareaVariants(${vArgs}), className)}
        {...props}
      />
      {errorMessage && <p className={cn('text-xs', isError ? 'text-destructive' : 'text-muted-foreground')}>{errorMessage}</p>}
    </div>
  );
}`
    : `export const Textarea = React.forwardRef<HTMLTextAreaElement, TextareaProps>(
  ({ className, ${vDestructure}label, helperText, error, disabled, id, ...props }, ref) => {
    const generatedId = React.useId();
    const inputId = id || generatedId;
    const isError = Boolean(error);
    const errorMessage = typeof error === 'string' ? error : helperText;

    return (
      <div className="flex flex-col gap-1.5 w-full">
        {label && <label htmlFor={inputId} className="text-sm font-medium text-foreground">{label}</label>}
        <textarea
          ref={ref}
          id={inputId}
          disabled={disabled}
          aria-invalid={isError ? 'true' : undefined}
          className={cn(textareaVariants(${vArgs}), className)}
          {...props}
        />
        {errorMessage && <p className={cn('text-xs', isError ? 'text-destructive' : 'text-muted-foreground')}>{errorMessage}</p>}
      </div>
    );
  }
);
Textarea.displayName = 'Textarea';`
}
`;
}

export function renderSelectTemplate(ctx: TemplateContext): string {
  const { spec, reactVersion, cnImportPath } = ctx;
  const cva = buildCvaDefinition(spec, 'selectVariants', [
    'flex',
    'w-full',
    'cursor-pointer',
    'focus-visible:outline-none',
    'disabled:cursor-not-allowed',
    'disabled:opacity-50',
  ]);
  const header = makeHeader(ctx, cva.hasRaw);
  const isReact19 = reactVersion >= 19;
  const { destructure: vDestructure, args: vArgs } = getVariantHelpers(cva.variantTypeProps);

  return `${header}
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '${cnImportPath}';

${cva.cvaCode}

export interface SelectProps
  extends Omit<React.SelectHTMLAttributes<HTMLSelectElement>, 'size'>,
    VariantProps<typeof selectVariants> {
  label?: string;
  helperText?: string;
  error?: boolean | string;
}

${
  isReact19
    ? `export function Select({ className, ${vDestructure}label, helperText, error, children, id, ref, ...props }: SelectProps & { ref?: React.Ref<HTMLSelectElement> }) {
  const generatedId = React.useId();
  const selectId = id || generatedId;
  const isError = Boolean(error);
  const errorMessage = typeof error === 'string' ? error : helperText;

  return (
    <div className="flex flex-col gap-1.5 w-full">
      {label && <label htmlFor={selectId} className="text-sm font-medium text-foreground">{label}</label>}
      <select ref={ref} id={selectId} aria-invalid={isError ? 'true' : undefined} className={cn(selectVariants(${vArgs}), className)} {...props}>
        {children}
      </select>
      {errorMessage && <p className={cn('text-xs', isError ? 'text-destructive' : 'text-muted-foreground')}>{errorMessage}</p>}
    </div>
  );
}`
    : `export const Select = React.forwardRef<HTMLSelectElement, SelectProps>(
  ({ className, ${vDestructure}label, helperText, error, children, id, ...props }, ref) => {
    const generatedId = React.useId();
    const selectId = id || generatedId;
    const isError = Boolean(error);
    const errorMessage = typeof error === 'string' ? error : helperText;

    return (
      <div className="flex flex-col gap-1.5 w-full">
        {label && <label htmlFor={selectId} className="text-sm font-medium text-foreground">{label}</label>}
        <select ref={ref} id={selectId} aria-invalid={isError ? 'true' : undefined} className={cn(selectVariants(${vArgs}), className)} {...props}>
          {children}
        </select>
        {errorMessage && <p className={cn('text-xs', isError ? 'text-destructive' : 'text-muted-foreground')}>{errorMessage}</p>}
      </div>
    );
  }
);
Select.displayName = 'Select';`
}
`;
}

export function renderCheckboxTemplate(ctx: TemplateContext): string {
  const { spec, reactVersion, cnImportPath } = ctx;
  const cva = buildCvaDefinition(spec, 'checkboxVariants', [
    'h-4',
    'w-4',
    'rounded',
    'border',
    'border-primary',
    'text-primary',
    'focus:ring-2',
    'focus:ring-primary',
    'disabled:cursor-not-allowed',
    'disabled:opacity-50',
  ]);
  const header = makeHeader(ctx, cva.hasRaw);
  const isReact19 = reactVersion >= 19;
  const { destructure: vDestructure, args: vArgs } = getVariantHelpers(cva.variantTypeProps);

  return `${header}
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '${cnImportPath}';

${cva.cvaCode}

export interface CheckboxProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type'>,
    VariantProps<typeof checkboxVariants> {
  label?: React.ReactNode;
}

${
  isReact19
    ? `export function Checkbox({ className, ${vDestructure}label, children, id, ref, ...props }: CheckboxProps & { ref?: React.Ref<HTMLInputElement> }) {
  const generatedId = React.useId();
  const checkboxId = id || generatedId;

  return (
    <label htmlFor={checkboxId} className="inline-flex items-center gap-2 cursor-pointer select-none">
      <input
        ref={ref}
        id={checkboxId}
        type="checkbox"
        className={cn(checkboxVariants(${vArgs}), className)}
        {...props}
      />
      {(label || children) && <span className="text-sm font-medium text-foreground">{label || children}</span>}
    </label>
  );
}`
    : `export const Checkbox = React.forwardRef<HTMLInputElement, CheckboxProps>(
  ({ className, ${vDestructure}label, children, id, ...props }, ref) => {
    const generatedId = React.useId();
    const checkboxId = id || generatedId;

    return (
      <label htmlFor={checkboxId} className="inline-flex items-center gap-2 cursor-pointer select-none">
        <input
          ref={ref}
          id={checkboxId}
          type="checkbox"
          className={cn(checkboxVariants(${vArgs}), className)}
          {...props}
        />
        {(label || children) && <span className="text-sm font-medium text-foreground">{label || children}</span>}
      </label>
    );
  }
);
Checkbox.displayName = 'Checkbox';`
}
`;
}

export function renderRadioTemplate(ctx: TemplateContext): string {
  const { spec, reactVersion, cnImportPath } = ctx;
  const cva = buildCvaDefinition(spec, 'radioVariants', [
    'h-4',
    'w-4',
    'rounded-full',
    'border',
    'border-primary',
    'text-primary',
    'focus:ring-2',
    'focus:ring-primary',
    'disabled:cursor-not-allowed',
    'disabled:opacity-50',
  ]);
  const header = makeHeader(ctx, cva.hasRaw);
  const isReact19 = reactVersion >= 19;
  const { destructure: vDestructure, args: vArgs } = getVariantHelpers(cva.variantTypeProps);

  return `${header}
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '${cnImportPath}';

${cva.cvaCode}

export interface RadioProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type'>,
    VariantProps<typeof radioVariants> {
  label?: React.ReactNode;
}

${
  isReact19
    ? `export function Radio({ className, ${vDestructure}label, children, id, ref, ...props }: RadioProps & { ref?: React.Ref<HTMLInputElement> }) {
  const generatedId = React.useId();
  const radioId = id || generatedId;

  return (
    <label htmlFor={radioId} className="inline-flex items-center gap-2 cursor-pointer select-none">
      <input
        ref={ref}
        id={radioId}
        type="radio"
        className={cn(radioVariants(${vArgs}), className)}
        {...props}
      />
      {(label || children) && <span className="text-sm font-medium text-foreground">{label || children}</span>}
    </label>
  );
}`
    : `export const Radio = React.forwardRef<HTMLInputElement, RadioProps>(
  ({ className, ${vDestructure}label, children, id, ...props }, ref) => {
    const generatedId = React.useId();
    const radioId = id || generatedId;

    return (
      <label htmlFor={radioId} className="inline-flex items-center gap-2 cursor-pointer select-none">
        <input
          ref={ref}
          id={radioId}
          type="radio"
          className={cn(radioVariants(${vArgs}), className)}
          {...props}
        />
        {(label || children) && <span className="text-sm font-medium text-foreground">{label || children}</span>}
      </label>
    );
  }
);
Radio.displayName = 'Radio';`
}
`;
}

export function renderSwitchTemplate(ctx: TemplateContext): string {
  const { spec, reactVersion, cnImportPath } = ctx;
  const cva = buildCvaDefinition(spec, 'switchVariants', [
    'inline-flex',
    'h-6',
    'w-11',
    'shrink-0',
    'cursor-pointer',
    'items-center',
    'rounded-full',
    'border-2',
    'border-transparent',
    'transition-colors',
    'focus-visible:outline-none',
    'disabled:cursor-not-allowed',
    'disabled:opacity-50',
  ]);
  const header = makeHeader(ctx, cva.hasRaw);
  const isReact19 = reactVersion >= 19;
  const { destructure: vDestructure, args: vArgs } = getVariantHelpers(cva.variantTypeProps);

  return `${header}
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '${cnImportPath}';

${cva.cvaCode}

export interface SwitchProps
  extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'onChange'>,
    VariantProps<typeof switchVariants> {
  checked?: boolean;
  onCheckedChange?: (checked: boolean) => void;
  label?: React.ReactNode;
}

${
  isReact19
    ? `export function Switch({
  className,
  ${vDestructure}checked = false,
  onCheckedChange,
  disabled,
  label,
  ref,
  ...props
}: SwitchProps & { ref?: React.Ref<HTMLButtonElement> }) {
  const [internalChecked, setInternalChecked] = React.useState(checked);
  const isControlled = props.checked !== undefined;
  const activeChecked = isControlled ? checked : internalChecked;

  const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {
    if (disabled) return;
    const next = !activeChecked;
    if (!isControlled) setInternalChecked(next);
    onCheckedChange?.(next);
    props.onClick?.(e);
  };

  const button = (
    <button
      ref={ref}
      type="button"
      role="switch"
      aria-checked={activeChecked}
      disabled={disabled}
      onClick={handleClick}
      className={cn(
        switchVariants(${vArgs}),
        activeChecked ? 'bg-primary' : 'bg-input',
        className
      )}
      {...props}
    >
      <span
        className={cn(
          'pointer-events-none block h-5 w-5 rounded-full bg-background shadow-lg ring-0 transition-transform',
          activeChecked ? 'translate-x-5' : 'translate-x-0'
        )}
      />
    </button>
  );

  if (label) {
    return (
      <label className="inline-flex items-center gap-2 cursor-pointer select-none">
        {button}
        <span className="text-sm font-medium text-foreground">{label}</span>
      </label>
    );
  }

  return button;
}`
    : `export const Switch = React.forwardRef<HTMLButtonElement, SwitchProps>(
  ({ className, ${vDestructure}checked = false, onCheckedChange, disabled, label, ...props }, ref) => {
    const [internalChecked, setInternalChecked] = React.useState(checked);
    const isControlled = props.checked !== undefined;
    const activeChecked = isControlled ? checked : internalChecked;

    const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {
      if (disabled) return;
      const next = !activeChecked;
      if (!isControlled) setInternalChecked(next);
      onCheckedChange?.(next);
      props.onClick?.(e);
    };

    const button = (
      <button
        ref={ref}
        type="button"
        role="switch"
        aria-checked={activeChecked}
        disabled={disabled}
        onClick={handleClick}
        className={cn(
          switchVariants(${vArgs}),
          activeChecked ? 'bg-primary' : 'bg-input',
          className
        )}
        {...props}
      >
        <span
          className={cn(
            'pointer-events-none block h-5 w-5 rounded-full bg-background shadow-lg ring-0 transition-transform',
            activeChecked ? 'translate-x-5' : 'translate-x-0'
          )}
        />
      </button>
    );

    if (label) {
      return (
        <label className="inline-flex items-center gap-2 cursor-pointer select-none">
          {button}
          <span className="text-sm font-medium text-foreground">{label}</span>
        </label>
      );
    }

    return button;
  }
);
Switch.displayName = 'Switch';`
}
`;
}

export function renderModalTemplate(ctx: TemplateContext): string {
  const { spec, reactVersion, cnImportPath } = ctx;
  const cva = buildCvaDefinition(spec, 'modalVariants', [
    'fixed',
    'left-[50%]',
    'top-[50%]',
    'z-50',
    'grid',
    'w-full',
    'max-w-lg',
    'translate-x-[-50%]',
    'translate-y-[-50%]',
    'gap-4',
    'border',
    'bg-background',
    'p-6',
    'shadow-lg',
    'duration-200',
    'sm:rounded-lg',
  ]);
  const header = makeHeader(ctx, cva.hasRaw);
  const isReact19 = reactVersion >= 19;
  const { destructure: vDestructure, args: vArgs } = getVariantHelpers(cva.variantTypeProps);

  return `${header}
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '${cnImportPath}';

${cva.cvaCode}

export interface ModalProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof modalVariants> {
  open?: boolean;
  onClose?: () => void;
  title?: React.ReactNode;
}

${
  isReact19
    ? `export function Modal({ className, ${vDestructure}open = false, onClose, title, children, ref, ...props }: ModalProps & { ref?: React.Ref<HTMLDivElement> }) {
  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="fixed inset-0 bg-black/50 backdrop-blur-sm transition-opacity" onClick={onClose} />
      <div ref={ref} role="dialog" aria-modal="true" className={cn(modalVariants(${vArgs}), className)} {...props}>
        {title && <h2 className="text-lg font-semibold leading-none tracking-tight">{title}</h2>}
        {children}
      </div>
    </div>
  );
}`
    : `export const Modal = React.forwardRef<HTMLDivElement, ModalProps>(
  ({ className, ${vDestructure}open = false, onClose, title, children, ...props }, ref) => {
    if (!open) return null;

    return (
      <div className="fixed inset-0 z-50 flex items-center justify-center">
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm transition-opacity" onClick={onClose} />
        <div ref={ref} role="dialog" aria-modal="true" className={cn(modalVariants(${vArgs}), className)} {...props}>
          {title && <h2 className="text-lg font-semibold leading-none tracking-tight">{title}</h2>}
          {children}
        </div>
      </div>
    );
  }
);
Modal.displayName = 'Modal';`
}
`;
}

export function renderTabsTemplate(ctx: TemplateContext): string {
  const { spec, reactVersion, cnImportPath } = ctx;
  const cva = buildCvaDefinition(spec, 'tabsVariants', [
    'inline-flex',
    'items-center',
    'justify-center',
    'rounded-md',
    'bg-muted',
    'p-1',
    'text-muted-foreground',
  ]);
  const header = makeHeader(ctx, cva.hasRaw);
  const isReact19 = reactVersion >= 19;
  const { destructure: vDestructure, args: vArgs } = getVariantHelpers(cva.variantTypeProps);

  return `${header}
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '${cnImportPath}';

${cva.cvaCode}

export interface TabsProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof tabsVariants> {
  value?: string;
  onValueChange?: (val: string) => void;
}

${
  isReact19
    ? `export function Tabs({ className, ${vDestructure}value, onValueChange, children, ref, ...props }: TabsProps & { ref?: React.Ref<HTMLDivElement> }) {
  return (
    <div ref={ref} role="tablist" className={cn(tabsVariants(${vArgs}), className)} {...props}>
      {children}
    </div>
  );
}`
    : `export const Tabs = React.forwardRef<HTMLDivElement, TabsProps>(
  ({ className, ${vDestructure}value, onValueChange, children, ...props }, ref) => {
    return (
      <div ref={ref} role="tablist" className={cn(tabsVariants(${vArgs}), className)} {...props}>
        {children}
      </div>
    );
  }
);
Tabs.displayName = 'Tabs';`
}
`;
}

export function renderGenericTemplate(ctx: TemplateContext): string {
  const { spec, reactVersion, cnImportPath } = ctx;
  const compName = spec.name;
  const cvaName = `${compName.charAt(0).toLowerCase() + compName.slice(1)}Variants`;
  const cva = buildCvaDefinition(spec, cvaName);

  const header = makeHeader(ctx, cva.hasRaw, true);
  const isReact19 = reactVersion >= 19;
  const role = spec.accessibility?.role ? `role="${spec.accessibility.role}"` : '';
  const { destructure: vDestructure, args: vArgs } = getVariantHelpers(cva.variantTypeProps);

  return `${header}
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '${cnImportPath}';

${cva.cvaCode}

export interface ${compName}Props
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof ${cvaName}> {}

${
  isReact19
    ? `export function ${compName}({ className, ${vDestructure}children, ref, ...props }: ${compName}Props & { ref?: React.Ref<HTMLDivElement> }) {
  return (
    <div ref={ref} ${role} className={cn(${cvaName}(${vArgs}), className)} {...props}>
      {children}
    </div>
  );
}`
    : `export const ${compName} = React.forwardRef<HTMLDivElement, ${compName}Props>(
  ({ className, ${vDestructure}children, ...props }, ref) => {
    return (
      <div ref={ref} ${role} className={cn(${cvaName}(${vArgs}), className)} {...props}>
        {children}
      </div>
    );
  }
);
${compName}.displayName = '${compName}';`
}
`;
}

export function selectTemplate(ctx: TemplateContext): string {
  const name = ctx.spec.name.toLowerCase();
  const category = (ctx.spec.category || '').toLowerCase();

  if (name === 'button' || category === 'button') return renderButtonTemplate(ctx);
  if (name === 'input' || category === 'input') return renderInputTemplate(ctx);
  if (name === 'textarea' || category === 'textarea') return renderTextareaTemplate(ctx);
  if (name === 'select' || category === 'select') return renderSelectTemplate(ctx);
  if (name === 'checkbox' || category === 'checkbox') return renderCheckboxTemplate(ctx);
  if (name === 'radio' || category === 'radio') return renderRadioTemplate(ctx);
  if (name === 'switch' || category === 'switch') return renderSwitchTemplate(ctx);
  if (name === 'card' || category === 'card') return renderCardTemplate(ctx);
  if (name === 'badge' || category === 'badge') return renderBadgeTemplate(ctx);
  if (name === 'modal' || name === 'dialog' || category === 'modal' || category === 'dialog')
    return renderModalTemplate(ctx);
  if (name === 'tabs' || category === 'tabs') return renderTabsTemplate(ctx);

  return renderGenericTemplate(ctx);
}
