import * as React from 'react';
import { Button, Card, Input } from '@/components/ui';

export default function App() {
  const [theme, setTheme] = React.useState<'light' | 'dark'>('light');

  const toggleTheme = () => {
    const nextTheme = theme === 'light' ? 'dark' : 'light';
    setTheme(nextTheme);
    document.documentElement.setAttribute('data-theme', nextTheme);
    if (nextTheme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  };

  return (
    <div className="min-h-screen bg-neutral-0 text-neutral-900 transition-colors duration-200 p-8 font-sans">
      <div className="max-w-5xl mx-auto space-y-12">
        {/* Header */}
        <header className="flex items-center justify-between border-b border-neutral-300 pb-6">
          <div>
            <h1 className="text-3xl font-bold tracking-tight text-primary-500">
              Frame-Relay Component Gallery
            </h1>
            <p className="text-sm text-neutral-500 mt-1">
              Live interactive gallery of components generated by Frame-Relay CLI from Figma tokens.
            </p>
          </div>
          <Button variant="Secondary" onClick={toggleTheme} className="cursor-pointer">
            {theme === 'light' ? '🌙 Dark Mode' : '☀️ Light Mode'}
          </Button>
        </header>

        {/* Section: Buttons */}
        <section className="space-y-6">
          <div className="border-b border-neutral-100 pb-2">
            <h2 className="text-xl font-semibold text-neutral-900">Button Component</h2>
            <p className="text-sm text-neutral-500">Every variant, size, and interactive state</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {/* Variants */}
            <div className="space-y-4 p-4 border border-neutral-100 rounded-lg">
              <h3 className="text-sm font-medium text-neutral-500 uppercase tracking-wider">
                Variants
              </h3>
              <div className="flex flex-wrap gap-3 items-center">
                <Button variant="Primary">Primary</Button>
                <Button variant="Secondary">Secondary</Button>
                <Button variant="Ghost">Ghost</Button>
              </div>
            </div>

            {/* Sizes */}
            <div className="space-y-4 p-4 border border-neutral-100 rounded-lg">
              <h3 className="text-sm font-medium text-neutral-500 uppercase tracking-wider">
                Sizes
              </h3>
              <div className="flex flex-wrap gap-3 items-center">
                <Button size="Medium">Medium</Button>
                <Button size="Large">Large</Button>
              </div>
            </div>

            {/* States & Icons */}
            <div className="space-y-4 p-4 border border-neutral-100 rounded-lg">
              <h3 className="text-sm font-medium text-neutral-500 uppercase tracking-wider">
                States & Slots
              </h3>
              <div className="flex flex-wrap gap-3 items-center">
                <Button loading>Loading</Button>
                <Button disabled>Disabled</Button>
                <Button leftIcon={<span>⚡</span>}>Action</Button>
              </div>
            </div>
          </div>
        </section>

        {/* Section: Input */}
        <section className="space-y-6">
          <div className="border-b border-neutral-100 pb-2">
            <h2 className="text-xl font-semibold text-neutral-900">Input Component</h2>
            <p className="text-sm text-neutral-500">
              Text input with labels, helpers, and error states
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Input
              label="Standard Email"
              type="email"
              placeholder="alex@example.com"
              helperText="We will never share your email address."
              leftIcon={<span className="text-xs">✉</span>}
            />

            <Input
              label="Validation Error State"
              defaultValue="invalid-input"
              error="Please enter a valid format."
              leftIcon={<span className="text-xs">⚠</span>}
            />

            <Input
              label="Disabled Input"
              disabled
              defaultValue="Disabled field value"
              helperText="This input cannot be edited."
            />

            <Input
              label="With Action Slot"
              placeholder="Search components..."
              rightIcon={<span className="text-xs">🔍</span>}
            />
          </div>
        </section>

        {/* Section: Card */}
        <section className="space-y-6">
          <div className="border-b border-neutral-100 pb-2">
            <h2 className="text-xl font-semibold text-neutral-900">Card Component</h2>
            <p className="text-sm text-neutral-500">
              Container layouts with headers, footers, and elevation
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card
              variant="Default"
              header={<span className="text-base text-neutral-900">Default Card</span>}
              footer={
                <div className="flex justify-end gap-2">
                  <Button variant="Ghost">Cancel</Button>
                  <Button variant="Primary">Save</Button>
                </div>
              }
            >
              <p className="text-sm text-neutral-500">
                This card uses the Default flat variant with subtle borders and standard spacing.
              </p>
            </Card>

            <Card
              variant="Elevated"
              header={<span className="text-base text-neutral-900">Elevated Card</span>}
              footer={
                <div className="flex justify-between items-center w-full">
                  <span className="text-xs text-neutral-500">Updated just now</span>
                  <Button variant="Secondary">Explore</Button>
                </div>
              }
            >
              <p className="text-sm text-neutral-500">
                This card uses the Elevated variant with tokens-mapped drop shadows for floating
                panels.
              </p>
            </Card>
          </div>
        </section>
      </div>
    </div>
  );
}
