// Generated by Frame-Relay from Frame-Relay Sample Kit, exported 2026-10-03T12:00:00.000Z. Safe to edit. Sync keeps your changes.
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '@/lib/cn';

export const buttonVariants = cva(
  'inline-flex items-center justify-center cursor-pointer transition-colors focus-visible:outline-none disabled:pointer-events-none flex flex-row justify-center items-center gap-2 px-4 py-2 w-fit h-fit bg-primary-500 rounded-md text-button hover:bg-primary-600 focus-visible:border border-focus-ring focus-visible:border-1 active:bg-primary-600 disabled:bg-neutral-300 aria-disabled:bg-neutral-300',
  {
    variants: {
      variant: {
        Primary: 'bg-primary-500 text-neutral-0',
        Secondary: 'bg-neutral-100 text-neutral-900 border border-neutral-300 border-1',
        Ghost: 'text-primary-500',
      },
      size: {
        Medium: 'rounded-md',
        Large: 'rounded-lg',
      },
    },
    defaultVariants: {
      variant: 'Primary',
      size: 'Medium',
    },
  },
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>, VariantProps<typeof buttonVariants> {
  leftIcon?: React.ReactNode;
  rightIcon?: React.ReactNode;
  loading?: boolean;
}

export function Button({
  className,
  variant,
  size,
  leftIcon,
  rightIcon,
  loading = false,
  disabled,
  children,
  type = 'button',
  ref,
  ...props
}: ButtonProps & { ref?: React.Ref<HTMLButtonElement> }) {
  return (
    <button
      ref={ref}
      type={type}
      disabled={disabled || loading}
      data-loading={loading ? 'true' : undefined}
      className={cn(buttonVariants({ variant, size }), className)}
      {...props}
    >
      {leftIcon && <span className="mr-2 inline-flex items-center shrink-0">{leftIcon}</span>}
      {children}
      {rightIcon && <span className="ml-2 inline-flex items-center shrink-0">{rightIcon}</span>}
    </button>
  );
}
