// Generated by Frame-Relay from Frame-Relay Sample Kit, exported 2026-10-03T12:00:00.000Z. Safe to edit. Sync keeps your changes.
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '@/lib/cn';

export const cardVariants = cva(
  'overflow-hidden transition-shadow flex flex-col gap-4 p-4 w-full h-fit bg-neutral-0 border border-neutral-100 border-1 rounded-lg',
  {
    variants: {
      variant: {
        Default: 'shadow-sm',
        Elevated: 'shadow-md',
      },
    },
    defaultVariants: {
      variant: 'Default',
    },
  },
);

export interface CardProps
  extends React.HTMLAttributes<HTMLDivElement>, VariantProps<typeof cardVariants> {
  header?: React.ReactNode;
  footer?: React.ReactNode;
}

export function Card({
  className,
  variant,
  header,
  footer,
  children,
  ref,
  ...props
}: CardProps & { ref?: React.Ref<HTMLDivElement> }) {
  return (
    <div ref={ref} role="region" className={cn(cardVariants({ variant }), className)} {...props}>
      {header && <div className="border-b border-border p-4 font-semibold">{header}</div>}
      <div className="p-4">{children}</div>
      {footer && <div className="border-t border-border p-4">{footer}</div>}
    </div>
  );
}
