// Generated by Frame-Relay from Frame-Relay Sample Kit, exported 2026-10-03T12:00:00.000Z. Safe to edit. Sync keeps your changes.
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '@/lib/cn';

export const inputVariants = cva(
  'flex w-full transition-colors focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50 flex flex-col gap-1 w-full h-fit text-body',
  {
    variants: {
      size: {
        Medium: '',
      },
    },
    defaultVariants: {
      size: 'Medium',
    },
  },
);

export interface InputProps
  extends
    Omit<React.InputHTMLAttributes<HTMLInputElement>, 'size'>,
    VariantProps<typeof inputVariants> {
  label?: string;
  helperText?: string;
  error?: boolean | string;
  leftIcon?: React.ReactNode;
  rightIcon?: React.ReactNode;
}

export function Input({
  className,
  type = 'text',
  size,
  label,
  helperText,
  error,
  leftIcon,
  rightIcon,
  disabled,
  id,
  ref,
  ...props
}: InputProps & { ref?: React.Ref<HTMLInputElement> }) {
  const generatedId = React.useId();
  const inputId = id || generatedId;
  const isError = Boolean(error);
  const errorMessage = typeof error === 'string' ? error : helperText;

  return (
    <div className="flex flex-col gap-1.5 w-full">
      {label && (
        <label htmlFor={inputId} className="text-sm font-medium text-foreground">
          {label}
        </label>
      )}
      <div className="relative flex items-center w-full">
        {leftIcon && (
          <span className="absolute left-3 inline-flex items-center pointer-events-none text-muted-foreground">
            {leftIcon}
          </span>
        )}
        <input
          ref={ref}
          id={inputId}
          type={type}
          disabled={disabled}
          aria-invalid={isError ? 'true' : undefined}
          className={cn(
            inputVariants({ size }),
            leftIcon && 'pl-10',
            rightIcon && 'pr-10',
            className,
          )}
          {...props}
        />
        {rightIcon && (
          <span className="absolute right-3 inline-flex items-center pointer-events-none text-muted-foreground">
            {rightIcon}
          </span>
        )}
      </div>
      {errorMessage && (
        <p className={cn('text-xs', isError ? 'text-destructive' : 'text-muted-foreground')}>
          {errorMessage}
        </p>
      )}
    </div>
  );
}
